backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: "FAQ's" # used in UI
    name: "faqs" # used in routes
    files:
      - label: "Class FAQ's"
        name: "class_faqs"
        file: "src/posts/class_faqs.json"
        fields:
          - label: Class FAQ List
            name: class_faq_list
            widget: list
            fields:
              - {label: Question, name: question, widget: string}
              - {label: Answer, name: answer, widget: string}
          - label: Upcoming Courses FAQ
            name: upcoming_courses_faq
            fields:
              - {label: Question, name: question, widget: string}
              - {label: Upcoming Courses Markdown, name: upcoming_courses_md, widget: markdown}