backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "/public" # Media files will be stored in the repo under images/uploads
public_folder: "/public" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: "FAQ's" # used in UI
    name: "faqs" # used in routes
    files:
      - label: "Class FAQ's"
        name: "class_faqs"
        file: "src/posts/faqs/class_faqs.json"
        fields:
          - label: Class FAQ List
            name: class_faq_list
            widget: list
            fields:
              - {label: Question, name: question, widget: string}
              - {label: Answer, name: answer, widget: string}
          - label: Upcoming Courses Question
            name: upcoming_courses_question
            widget: string
          - label:  Upcoming Courses Answer
            name: upcoming_courses_answer
            widget: markdown
      - label: "Volunteer FAQ's"
        name: "volunteer_faqs"
        file: "src/posts/faqs/volunteer_faqs.json"
        fields:
          - label: Teacher FAQ List
            name: teacher_faq_list
            widget: list
            fields:
              - {label: Question, name: question, widget: string}
              - {label: Answer, name: answer, widget: string}
          - label: Publicity FAQ List
            name: publicity_faq_list
            widget: list
            fields:
              - {label: Question, name: question, widget: string}
              - {label: Answer, name: answer, widget: string}
  - label: "Bylaws and Minutes" # used in UI
    name: "bylaws_minutes" # used in routes
    files:
      - label: "Corporation Bylaws"
        name: "corp_bylaws"
        file: "src/posts/downloads/corp_bylaws.json"
        fields:
          - label: "Corporation Bylaws"
            name: "corp_bylaws_list"
            widget: list
            fields:
              - {label: Date, name: date, widget: date, default: "", format: "MMMM Do, YYYY"}
              - {label: Item Name, name: item_name, widget: string}
              - label: file
                name: "file_path"
                widget: file
                media_folder: '/public/uploads/downloads/corpsbylaws'
      - label: "Meeting Minutes and Agendas"
        name: "meeting_records"
        file: "src/posts/downloads/meeting_records.json"
        fields:
          - label: "Meeting Minutes and Agendas"
            name: "meeting_records_list"
            widget: list
            fields:
              - {label: Date, name: date, widget: date, default: "", format: "MMMM Do, YYYY"}
              - {label: Item Name, name: item_name, widget: string}
              - label: Meeting Minute File
                name: "meeting_minute_file_path"
                widget: file
                media_folder: '/public/uploads/downloads/meetingrecords'
              - label: Agenda File
                name: "agenda_file_path"
                widget: file
                media_folder: '/public/uploads/downloads/meetingrecords'
  - label: "Newsletters" # used in UI
    name: "newsletters" # used in routes
    files:
      - label: "Newsletters"
        name: "newsletters"
        file: "src/posts/newsletters.json"
        fields:
          - label: "Newsletters"
            name: "newsletters_list"
            widget: list
            fields:
              - {label: Date, name: date, widget: date, default: "", format: "MMMM YYYY"}
              - label: file
                name: "file_path"
                widget: file
                media_folder: '/public/uploads/newsletters'
  - label: "Courses" # used in UI
    name: "courses" # used in routes
    files:
      - label: "Courses"
        name: "curses"
        file: "src/posts/courses.json"
        fields:
          - label: "Courses"
            name: "courses_list"
            widget: list
            fields:
              - {label: Course Name, name: course_name, widget: string}
              - label: Image
                name: "file_path"
                widget: image
                media_folder: '/public/uploads/coursesimg'
  - label: "Syllabi" # used in UI
    name: "syllabi" # used in routes
    files:
      - label: "Syllabi"
        name: "syllabi"
        file: "src/posts/syllabi.json"
        fields:
          - label: "Syllabi"
            name: "syllabi_list"
            widget: list
            fields:
              - {label: Language (Add language in native tongue. Ex. If Chinese => 中文; If French => FRANÇAIS), name: language, widget: string}
              - {label: Link to Syllabi Document, name: link, widget: string}
              - label: Flag Image
                name: "file_path"
                widget: image
                media_folder: '/public/uploads/flagimg'
  - label: "Editable Texts" # used in UI
    name: "editable_texts" # used in routes
    files:
      - label: "Individual Learners and Schools"
        name: "ind_learners_and_schools"
        file: "src/posts/ind_learners_and_schools.json"
        fields:
          - {label: "Course Overview Bold Text", name: "indlearners_bold_text", widget: string}
          - {label: "Course Overview Body Text", name: "indlearners_body_text", widget: markdown}
  - label: "Register Form" # used in UI
    name: "register_form" # used in routes
    files:
      - label: "Register Form"
        name: "register_form"
        file: "src/posts/register_form.json"
        fields:
          - label: "Google Form Embed Code"
            name: "register_form_code"
            widget: code
  - label: "Enroll Links" # used in UI
    name: "enroll_links" # used in routes
    files:
      - label: "Enroll Links"
        name: "enroll_links"
        file: "src/posts/enroll_links.json"
        fields:
          - label: "Enroll Link for Ind Learners and Schools"
            name: "link"
            widget: string
  - label: "Teacher/TA/Intern Overviews" # used in UI
    name: "teacher_ta_intern_overviews" # used in routes
    files:
      - label: "Teacher Overview"
        name: "teacher_overview"
        file: "src/posts/teacher_overview.json"
        fields:
          - label: "Overview"
            name: "overview"
            widget: markdown
          - label: "Scheduling"
            name: "Scheduling"
            widget: markdown
          - label: "Tasks"
            name: "Tasks"
            widget: markdown
          - label: "Curriculum"
            name: "Curriculum"
            widget: markdown
          - label: "Time Commitment"
            name: "Time Commitment"
            widget: markdown
          - label: "Benefits"
            name: "Benefits"
            widget: markdown
          - label: "Requirments"
            name: "Requirments"
            widget: markdown
          - label: "Beneficial Qualifications"
            name: "Beneficial Qualifications"
            widget: markdown
          - label: "questions"
            name: "questions"
            widget: markdown