backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "/public" # Media files will be stored in the repo under images/uploads
public_folder: "/public" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: "FAQ's" # used in UI
    name: "faqs" # used in routes
    files:
      - label: "Class FAQ's"
        name: "class_faqs"
        file: "src/posts/faqs/class_faqs.json"
        fields:
          - label: Class FAQ List
            name: class_faq_list
            widget: list
            fields:
              - {label: Question, name: question, widget: string}
              - {label: Answer, name: answer, widget: string}
          - label: Upcoming Courses Question
            name: upcoming_courses_question
            widget: string
          - label:  Upcoming Courses Answer
            name: upcoming_courses_answer
            widget: markdown
      - label: "Volunteer FAQ's"
        name: "volunteer_faqs"
        file: "src/posts/faqs/volunteer_faqs.json"
        fields:
          - label: Teacher FAQ List
            name: teacher_faq_list
            widget: list
            fields:
              - {label: Question, name: question, widget: string}
              - {label: Answer, name: answer, widget: string}
          - label: Publicity FAQ List
            name: publicity_faq_list
            widget: list
            fields:
              - {label: Question, name: question, widget: string}
              - {label: Answer, name: answer, widget: string}
  - label: "Bylaws and Minutes" # used in UI
    name: "bylaws_minutes" # used in routes
    files:
      - label: "Corporation Bylaws"
        name: "corp_bylaws"
        file: "src/posts/downloads/corp_bylaws.json"
        fields:
          - label: "Corporation Bylaws"
            name: "corp_bylaws_list"
            widget: list
            fields:
              - {label: Date, name: date, widget: date, default: "", format: "MMMM Do, YYYY"}
              - {label: Item Name, name: item_name, widget: string}
              - label: file
                name: "file_path"
                widget: file
                media_folder: '/uploads/downloads/corpsbylaws'
                public_folder: '/uploads/downloads/corpsbylaws'
      - label: "Meeting Minutes and Agendas"
        name: "meeting_records"
        file: "src/posts/downloads/meeting_records.json"
        fields:
          - label: "Meeting Minutes and Agendas"
            name: "meeting_records_list"
            widget: list
            fields:
              - {label: Date, name: date, widget: date, default: "", format: "MMMM Do, YYYY"}
              - {label: Item Name, name: item_name, widget: string}
              - label: Meeting Minute File
                name: "meeting_minute_file_path"
                widget: file
                media_folder: '/uploads/downloads/meetingrecords'
                public_folder: '/uploads/downloads/meetingrecords'
              - label: Agenda File
                name: "agenda_file_path"
                widget: file
                media_folder: '/uploads/downloads/meetingrecords'
                public_folder: '/uploads/downloads/meetingrecords'